### ISSUE TITLE
 [Question or Bug] Encoding / decoding (RFC3986)

### ISSUE THREAD

**Issue by Gounlaf** [byjg/uri#3]
Hi,

I'm encoutering an issue with encoding/decoding password part.
The problem is descrived on another project with the same issue (https://github.com/thephpleague/uri-components/issues/28) ; can you take a look at it?

Thanks,

Regards

Edit: right now, I reset password myself

```php
$anotherUriImpl = AnotherUriImplementation('some_db_uri');
$uri = (new MigrationUri((string)$anotherUriImpl)
    ->withUserInfo($anotherUriImpl->getUser(), $anotherUriImpl->getPass());
```

**Comment by byjg** [comment]
I added some unit tests to address it. It seems it is working as expected. Please confirm to me.

**Comment by Gounlaf** [comment]
Okay, my bad, in fact the issue is not completely tight to the problem.

I'm using the league implementation because it's more generic than the `psr/uri`.
So I convert my `league/uri` object "to string", which it encode user/password special chars.
When creating a `byjg/uri` from this string, password is not correctly decoded (`league/uri` had the same issue, they fixed it).

```php
$uri = (new Uri('http://example.com/path/to?q=foo%20bar#section-42'))
    ->withUserInfo('user', "O=+9zLZ}%{z+:tC");

$uriLeague = (\League\Uri\Uri::createFromString('http://example.com/path/to?q=foo%20bar#section-42'))
    ->withUserInfo('user', "O=+9zLZ}%{z+:tC");

var_dump((string)$uri); // http://user:O=+9zLZ}%{z+:tC@example.com/path/to?q=foo+bar#section-42
var_dump((string)$uriLeague); // http://user:O=+9zLZ%7D%25%7Bz+:tC@example.com/path/to?q=foo%20bar#section-42
```

I hope it's more clear.

Thanks

**Comment by byjg** [comment]
So, let me see if I understood correctly: I have to set plain password with no encoding and when I get it in full I have to get it url encoded ?

And Just out of curiousity, what do you mean by  _the league implementation is **more generic** than the psr/uri._ ?

**Comment by Gounlaf** [comment]
> So, let me see if I understood correctly: I have to set plain password with no encoding and when I get it in full I have to get it url encoded ?

If I'm right:
- when manipulating value, it should be decoded; in userland / as a developer using the library, I shouldn't have to decode the different components of the URI.
- when "output it" (any kind of serialization?), it must be encoded (according to RFC).

> And Just out of curiousity, what do you mean by _the league implementation is **more generic** than the psr/uri._ ?

- re-reading PSR-7, it always talk about HTTP messages / HTTP protocol.
- https://uri.thephpleague.com/uri/6.0/ (Overview)

**Comment by byjg** [comment]
If there is nothing else, I'll merge it and generate a new major version.

**Comment by Gounlaf** [comment]
> If there is nothing else

Hi!
Sorry, forgot to comment ><

Well, It seems to be fine for the **password**.
But what about the other parts? I'm not an expert of the RFC, but it's not clear =/

At least password is covered :)
And I didn't have problems with the other parts.

**Comment by Gounlaf** [comment]
Hi @byjg,

I figured out I was wrong about your fix. If I'm right the instantiation from a string is bugged.

In `\ByJG\Util\Uri` constructor:
```php
$this->withUserInfo($user, $this->getFromArray($parsed, 'pass'));
```

It should be:

```php
$this->withUserInfo(rawurldecode($user), rawurldecode($this->getFromArray($parsed, 'pass')));
```

Because the input string must be correctly encoded.

```php
$uri = \ByJG\Util\Uri::getInstanceFromString('http://example.com/path/to?q=foo%20bar#section-42')
    ->withUserInfo('user', "O=+9zLZ}%{z+:tC");

$uri2 = \ByJG\Util\Uri::getInstanceFromString((string)$uri);

$this->assertSame((string)$uri, (string)$uri2);// return false
```

**Comment by byjg** [comment]
I followed your suggestion and I did some other changes to match with RPC3986.

Take a look here:
https://github.com/byjg/uri/compare/2.0.1?expand=1

**Comment by Gounlaf** [comment]
> I followed your suggestion and I did some other changes to match with RPC3986.
> 
> Take a look here:
> https://github.com/byjg/uri/compare/2.0.1?expand=1

It seems to work again as expected with this version ;)

**Comment by byjg** [comment]
Done. Release 2.0.1.

**Comment by Gounlaf** [comment]
> Done. Release 2.0.1.

Thanks you @byjg ;)
