### ISSUE TITLE
Uri instances must be immutable

### ISSUE THREAD

**Issue by UlrichEckhardt** [byjg/uri#6]
See e.g. https://github.com/php-fig/http-message/blob/master/src/UriInterface.php#L176 for the `withScheme` method. That will have to be 
```
    public function withScheme($value)
    {
        $res = clone $this;
        $res->scheme = strtolower($value);
        return $res;
    }
```
The same applies to other `with...` methods.

**Comment by byjg** [comment]
It make senses. In fact I dont like of this concept of clone the object  but you are completely right. If has a specification I should be compliance to it. 

I'll work on that.

**Comment by byjg** [comment]
Implementation is done. Now I have to upgrade other components I have to support this new behavior.

**Comment by byjg** [comment]
Release `2.1.0` created with the issue fix.
